In [1]:
import pandas as pd

marks = [50, 60, 65, 70, 75, 80, 85, 90]
df = pd.DataFrame({"marks": marks})
df

   marks
0     50
1     60
2     65
3     70
4     75
5     80
6     85
7     90

In [2]:
# or

import pandas as pd

marks = pd.Series([50, 60, 65, 70, 75, 80, 85, 90])

marks.mean()
marks.median()
marks.mode()

0    50
1    60
2    65
3    70
4    75
5    80
6    85
7    90
dtype: int64

In [3]:
mean_ = df["marks"].mean()
median_ = df["marks"].median()
mode_ = df["marks"].mode()[0]

mean_, median_, mode_

(71.875, 72.5, 50)

In [4]:
#Replace 90 with 900

marks2 = [50, 60, 65, 70, 75, 80, 85, 900]
df2 = pd.DataFrame({"marks": marks2})
df2["marks"].mean()

173.125

In [5]:
temps = [29, 31, 33, 33, 32, 31, 30]
df = pd.DataFrame({"temp": temps})

var_ = df["temp"].var()
std_ = df["temp"].std()

var_, std_

(2.2380952380952377, 1.4960264830861911)

In [6]:
weights = [2.5,3.0,3.2,3.3,3.4,3.5,3.6,3.9,4.0,4.5]
df = pd.DataFrame({"w": weights})

df

     w
0  2.5
1  3.0
2  3.2
3  3.3
4  3.4
5  3.5
6  3.6
7  3.9
8  4.0
9  4.5

In [7]:
import numpy as np

p25 = np.percentile(df["w"], 25) # [same]
p50 = df["w"].quantile(0.50) # [same]  
p75 = df["w"].quantile(0.75)
iqr = p75 - p25

p25, p50, p75, iqr

(3.225, 3.45, 3.825, 0.6000000000000001)

In [8]:
# Outlier limit
lower = p25 - 1.5*iqr
upper = p75 + 1.5*iqr
print("Q3 Lower Fence:", lower)
print("Q3 Upper Fence:", upper)

Q3 Lower Fence: 2.325
Q3 Upper Fence: 4.7250000000000005

In [9]:
mu = 50
sigma = 10

# a) Z score for x=65
z_65 = (65 - mu)/sigma
print("\nQ4 Z for x=65:", z_65)

# b) x from Z = -2.5
x_neg = mu + (-2.5)*sigma
print("Q4 x for Z=-2.5:", x_neg)

Q4 Z for x=65: 1.5
Q4 x for Z=-2.5: 25.0

## Or

In [11]:
import pandas as pd

marks = pd.Series([50, 60, 65, 70, 75, 80, 85, 90])

marks.mean()
marks.median()
marks.mode()

0    50
1    60
2    65
3    70
4    75
5    80
6    85
7    90
dtype: int64

In [12]:
marks_outlier = pd.Series([50, 60, 65, 70, 75, 80, 85, 900])

marks_outlier.mean()

173.125

 Module 1 – Part A

In [ ]:
temps = pd.Series([29, 31, 33, 33, 32, 31, 30])

temps.var()
temps.std()

Module 1 – Part B

In [18]:
cats = pd.Series([2.5, 3.0, 3.2, 3.3, 3.4, 3.5, 3.6, 3.9, 4.0, 4.5])

Q1 = cats.quantile(0.25)
Q2 = cats.quantile(0.50)
Q3 = cats.quantile(0.75)
IQR = (Q3 - Q1).round(2)

Q1, Q2, Q3, IQR

(3.225, 3.45, 3.825, 0.6)

In [ ]:
## Outlier Range
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

lower, upper

In [ ]:
# Z-Score (x = 65)
mu = 50
sigma = 10
x = 65

z = (x - mu) / sigma
z

In [ ]:
# x for Z = -2.5
z = -2.5
x = mu + z * sigma
x

In [1]:
# Basic Probability

total = 100
A = 40
B = 50
A_and_B = 20

P_A = A/total
P_B = B/total
P_A_and_B = A_and_B/total
P_A_given_B = A_and_B / B

P_A, P_B, P_A_and_B, P_A_given_B

(0.4, 0.5, 0.2, 0.4)

In [4]:
# Bayes Theorem

spam = 100
free_spam = 40
free_nonspam = 60

P_S = spam / 1000
P_F_given_S = free_spam / spam
P_F = (40 + 60) / 1000

P_S_given_F = (P_F_given_S * P_S) / P_F
P_S_given_F

0.4000000000000001

In [5]:
# Hospital Triage Model

import pandas as pd

cm = pd.DataFrame(
    [[120,42,18],
     [60,612,48],
     [45,90,165]],
    index=["U","N","R"],
    columns=["U","N","R"]
)
cm

     U    N    R
U  120   42   18
N   60  612   48
R   45   90  165